#include "futurist_plugin.h"
#include <FuturistPluginAssets.h>
#include "source/LfoVisualizer.cpp"
#include "source/CustomLookAndFeel.cpp"
#include "source/JsonSerializer.cpp"
#include "source/Parameters.cpp"
#include "source/PluginEditor.cpp"
#include "source/PluginProcessor.cpp"
#include "source/CSharedMemory.cpp"
